version: "3"

services: 
    db:
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
            - '5432:5432'
    app:
        build: .
        depends_on:
            - db
        command: yarn start:dev
        ports: 
            - "3000:3000"
        volumes: 
            - .:/usr/app