version: "3"

services: 
    app:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        environment: 
            DATABASE_URL: postgres://user:password@postgres:5432/postgres
            NODE_ENV: development
            PORT: 3000
        ports: 
            - "3000:3000"
        volumes: 
            - .:/usr/app
        networks: 
            - backend

    postgres: 
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        networks: 
            - backend

networks: 
    backend:
        name: backend